function [f, fPrime, lambda, lambdaPrime] = def_half_f_fPrime_lambda_lambdaPrime(dom)
    y = chebfun('y', dom);
    lambda = @(U) sum((y+U).*diff(U))./sum(U-y.*diff(U));
    lambdaPrime = @(U,U_tilde) ( ...
        (sum(U_tilde.*diff(U))+sum((y+U).*diff(U_tilde))).*sum(U-y.*diff(U)) ...
        -sum((y+U).*diff(U)).*sum(U_tilde-y.*diff(U_tilde)) ...
        ) / ( ...
        ((sum(U-y.*diff(U)))^2)...
        );
    f = @(U) - lambda(U).*U + ((1+lambda(U)).*y+U).*diff(U);
    fPrime = @(U,U_tilde) ( ...
        - lambdaPrime(U,U_tilde).*U ...
        - lambda(U) .* U_tilde ...
        + (lambdaPrime(U,U_tilde).*y+U_tilde).*diff(U) + ...
        ((1+lambda(U)).*y+U).*diff(U_tilde) ...
        );
end
